<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <PackageReference Include="OPCFoundation.NetStandard.Opc.Ua.Client" />
    <PackageReference Include="OPCFoundation.NetStandard.Opc.Ua.Client.ComplexTypes" />
  </ItemGroup>
  <ItemGroup>
    <InternalsVisibleTo Include="OpcUaBrowser.Core.Tests" />
  </ItemGroup>
</Project>
